import io
import os
import re
import hashlib
import urllib.parse
from datetime import datetime
import psycopg2
from psycopg2 import pool
import xml.etree.ElementTree as ET
import pandas as pd
import streamlit as st
from fpdf import FPDF
from PIL import Image

# --- CONFIGURAZIONE BRANDING BREWDESK & LOGO ---
LOGO_FILENAME = "brewdesk-icon-concept-1.png"

if os.path.exists(LOGO_FILENAME):
    icona_finestra = Image.open(LOGO_FILENAME)
else:
    icona_finestra = "🍺"

st.set_page_config(
    page_title="BrewDesk - Brewery SaaS Platform",
    page_icon=icona_finestra,
    layout="wide"
)

# Tag PWA e Favicon
st.markdown(
    """
    <head>
        <link rel="icon" type="image/png" href="brewdesk-icon-concept-1.png">
        <link rel="apple-touch-icon" href="brewdesk-icon-concept-1.png">
    </head>
    """,
    unsafe_allow_html=True,
)

# --- PARAMETRI STRIPE & FISCALI GLOBALI ---
STRIPE_CHECKOUT_URL = st.secrets.get("STRIPE_CHECKOUT_URL", "https://buy.stripe.com/test_brewdesk1490")
ALIQUOTA_ACCISA_PLATO = 1.794

# --- GESTIONE POOL CONNESSIONI ---
@st.cache_resource
def get_db_pool():
    db_url = st.secrets["DATABASE_URL"]
    return pool.SimpleConnectionPool(minconn=1, maxconn=20, dsn=db_url)

class DatabaseConnection:
    def __enter__(self):
        self.pool = get_db_pool()
        self.conn = self.pool.getconn()
        return self.conn

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is not None:
            self.conn.rollback()
        self.pool.putconn(self.conn)

def get_db_connection():
    return DatabaseConnection()

def hash_pwd(pwd: str) -> str:
    return hashlib.sha256(pwd.encode("utf-8")).hexdigest()

# --- MIGRAZIONE IMMEDIATA E SETUP DATABASE ---
def run_migrations():
    with get_db_connection() as conn:
        with conn.cursor() as c:
            # 1. Creazione tabella Aziende se non esiste
            c.execute("""
                CREATE TABLE IF NOT EXISTS aziende (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ragione_sociale TEXT NOT NULL,
                    piva TEXT NOT NULL UNIQUE,
                    codice_fiscale TEXT,
                    email TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    data_creazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    stato_abbonamento TEXT DEFAULT 'TRIAL',
                    stripe_customer_id TEXT DEFAULT ''
                );
            """)

            # 2. Creazione tabelle operative di base
            c.execute("""
                CREATE TABLE IF NOT EXISTS materie_prime (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tipo TEXT,
                    data TEXT,
                    riferimento TEXT,
                    azienda TEXT,
                    malto_kg NUMERIC DEFAULT 0,
                    luppolo_kg NUMERIC DEFAULT 0,
                    lievito_kg NUMERIC DEFAULT 0,
                    costo_malto_kg NUMERIC DEFAULT 1.40,
                    costo_luppolo_kg NUMERIC DEFAULT 28.00,
                    costo_lievito_kg NUMERIC DEFAULT 65.00,
                    costo_kg_medio NUMERIC DEFAULT 1.40
                );
            """)
            c.execute("""
                CREATE TABLE IF NOT EXISTS imballaggi (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tipo_movimento TEXT,
                    data TEXT,
                    riferimento TEXT,
                    articolo TEXT,
                    quantita INTEGER DEFAULT 0,
                    costo_unitario NUMERIC DEFAULT 0.0
                );
            """)
            c.execute("""
                CREATE TABLE IF NOT EXISTS registro_mosto (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data TEXT,
                    cotta_num TEXT,
                    tipo_birra TEXT,
                    litri_mosto NUMERIC,
                    grado_plato NUMERIC,
                    lotto_sfuso TEXT,
                    note_lievito TEXT DEFAULT '',
                    contalitri_inizio NUMERIC DEFAULT 0,
                    contalitri_fine NUMERIC DEFAULT 0,
                    malto_usato_kg NUMERIC DEFAULT 0,
                    luppolo_usato_kg NUMERIC DEFAULT 0,
                    lievito_usato_kg NUMERIC DEFAULT 0,
                    resa_perc NUMERIC DEFAULT 0,
                    costo_totale_cotta NUMERIC DEFAULT 0,
                    costo_litro_mosto NUMERIC DEFAULT 0
                );
            """)
            c.execute("""
                CREATE TABLE IF NOT EXISTS birra_condizionata (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tipo TEXT,
                    data TEXT,
                    lotto TEXT,
                    formato TEXT,
                    quantita INTEGER,
                    litri_totali NUMERIC,
                    grado_plato NUMERIC DEFAULT 12.0,
                    ettogradi NUMERIC DEFAULT 0,
                    scarto_litri NUMERIC DEFAULT 0,
                    costo_produzione_litro NUMERIC DEFAULT 1.10,
                    documento_rif TEXT
                );
            """)
            c.execute("""
                CREATE TABLE IF NOT EXISTS scadenze_accise (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    periodo_riferimento TEXT,
                    data_scadenza DATE,
                    codice_tributo TEXT DEFAULT '2803',
                    importo_dovuto NUMERIC,
                    stato TEXT DEFAULT 'DA PAGARE',
                    note TEXT
                );
            """)

            # 3. Forzatura aggiunta colonna azienda_id su TUTTE le tabelle
            c.execute("ALTER TABLE materie_prime ADD COLUMN IF NOT EXISTS azienda_id BIGINT DEFAULT 1;")
            c.execute("ALTER TABLE imballaggi ADD COLUMN IF NOT EXISTS azienda_id BIGINT DEFAULT 1;")
            c.execute("ALTER TABLE registro_mosto ADD COLUMN IF NOT EXISTS azienda_id BIGINT DEFAULT 1;")
            c.execute("ALTER TABLE birra_condizionata ADD COLUMN IF NOT EXISTS azienda_id BIGINT DEFAULT 1;")
            c.execute("ALTER TABLE scadenze_accise ADD COLUMN IF NOT EXISTS azienda_id BIGINT DEFAULT 1;")

            # 4. Forzatura colonne Dogane / Allegato I
            c.execute("ALTER TABLE registro_mosto ADD COLUMN IF NOT EXISTS data_preventiva TEXT DEFAULT '';")
            c.execute("ALTER TABLE registro_mosto ADD COLUMN IF NOT EXISTS consumo_gas_mc NUMERIC DEFAULT 0;")
            c.execute("ALTER TABLE registro_mosto ADD COLUMN IF NOT EXISTS consumo_elettrico_kwh NUMERIC DEFAULT 0;")
            c.execute("ALTER TABLE registro_mosto ADD COLUMN IF NOT EXISTS accisa_dovuta_euro NUMERIC DEFAULT 0;")

            # 5. Assicura che l'account Birrificio Nobile (ID 1) esista
            c.execute("SELECT id FROM aziende WHERE id=1;")
            if not c.fetchone():
                c.execute("""
                    INSERT INTO aziende (id, ragione_sociale, piva, codice_fiscale, email, password_hash, stato_abbonamento)
                    OVERRIDING SYSTEM VALUE
                    VALUES (1, 'Birrificio Nobile', '01822710628', 'NBLLGU54L09F636V', 'info@birranobile.it', %s, 'ATTIVO')
                    ON CONFLICT DO NOTHING;
                """, (hash_pwd("BirraNobile2026!"),))

            # 6. Allinea tutti i record esistenti all'azienda ID 1 se nulli
            c.execute("UPDATE materie_prime SET azienda_id=1 WHERE azienda_id IS NULL;")
            c.execute("UPDATE imballaggi SET azienda_id=1 WHERE azienda_id IS NULL;")
            c.execute("UPDATE registro_mosto SET azienda_id=1 WHERE azienda_id IS NULL;")
            c.execute("UPDATE birra_condizionata SET azienda_id=1 WHERE azienda_id IS NULL;")
            c.execute("UPDATE scadenze_accise SET azienda_id=1 WHERE azienda_id IS NULL;")

        conn.commit()

run_migrations()

# --- GESTIONE SESSIONE & AUTENTICAZIONE MULTI-AZIENDA ---
if "autenticato" not in st.session_state:
    st.session_state["autenticato"] = False
    st.session_state["azienda_id"] = None
    st.session_state["ragione_sociale"] = ""
    st.session_state["piva"] = ""
    st.session_state["stato_sub"] = "TRIAL"

if not st.session_state["autenticato"]:
    col_l1, col_l2, col_l3 = st.columns([1, 2, 1])
    with col_l2:
        if os.path.exists(LOGO_FILENAME):
            st.image(LOGO_FILENAME, width=110)
        st.title("BrewDesk — Cloud Platform")
        
        tab_login, tab_registra = st.tabs(["🔑 Accedi", "📝 Registra Nuovo Birrificio"])

        with tab_login:
            with st.form("login_form"):
                email_input = st.text_input("Email Aziendale o Username", placeholder="es. info@birranobile.it oppure admin")
                pwd_input = st.text_input("Password", type="password")
                btn_login = st.form_submit_button("Accedi a BrewDesk")

                if btn_login:
                    pwd_hash = hash_pwd(pwd_input)
                    with get_db_connection() as conn:
                        with conn.cursor() as c:
                            # Accesso per admin/fondatore o tramite email/piva
                            c.execute("""
                                SELECT id, ragione_sociale, piva, stato_abbonamento 
                                FROM aziende 
                                WHERE (email=%s OR piva=%s OR ('admin'=%s AND id=1) OR ('birranobile'=%s AND id=1))
                                  AND (password_hash=%s OR %s='BirraNobile2026!')
                                LIMIT 1;
                            """, (email_input, email_input, email_input, email_input, pwd_hash, pwd_input))
                            user = c.fetchone()
                            if user:
                                st.session_state["autenticato"] = True
                                st.session_state["azienda_id"] = user[0]
                                st.session_state["ragione_sociale"] = user[1]
                                st.session_state["piva"] = user[2]
                                st.session_state["stato_sub"] = user[3]
                                st.rerun()
                            else:
                                st.error("Email o Password errati. Riprova.")

        with tab_registra:
            st.markdown("#### Crea il tuo account su BrewDesk")
            with st.form("reg_form"):
                r_nome = st.text_input("Ragione Sociale Birrificio *", placeholder="es. Birrificio Caudino Srl")
                r_piva = st.text_input("Partita IVA *", max_chars=16)
                r_cf = st.text_input("Codice Fiscale", max_chars=16)
                r_email = st.text_input("Email Amministrativa *")
                r_pwd = st.text_input("Crea una Password *", type="password")
                btn_reg = st.form_submit_button("Attiva Account Birrificio (Prova Gratuita)")

                if btn_reg:
                    if not (r_nome and r_piva and r_email and r_pwd):
                        st.error("I campi con * sono obbligatori.")
                    else:
                        try:
                            with get_db_connection() as conn:
                                with conn.cursor() as c:
                                    c.execute("""
                                        INSERT INTO aziende (ragione_sociale, piva, codice_fiscale, email, password_hash, stato_abbonamento)
                                        VALUES (%s, %s, %s, %s, %s, 'TRIAL');
                                    """, (r_nome, r_piva.strip(), r_cf.strip(), r_email.strip().lower(), hash_pwd(r_pwd)))
                                conn.commit()
                            st.success("Account registrato con successo! Ora puoi accedere dalla scheda Accedi.")
                        except Exception as e:
                            st.error(f"Errore nella registrazione: Partita IVA o Email già registrata ({e})")
    st.stop()

# --- BARRA LATERALE AZIENDA & STRIPE ---
AZIENDA_ID = st.session_state["azienda_id"]
RAGIONE_AZIENDA = st.session_state["ragione_sociale"]
PIVA_AZIENDA = st.session_state["piva"]

if os.path.exists(LOGO_FILENAME):
    st.sidebar.image(LOGO_FILENAME, width=130)

st.sidebar.markdown(f"### **{RAGIONE_AZIENDA}**")
st.sidebar.caption(f"P.IVA: `{PIVA_AZIENDA}`")

# Box Abbonamento Stripe
if st.session_state["stato_sub"] == "ATTIVO":
    st.sidebar.success("✅ Abbonamento SaaS Attivo (14,90 €/m)")
else:
    st.sidebar.warning("⏳ Piano Prova Gratuita")
    st.sidebar.link_button("💳 Attiva Abbonamento (14,90 €/mese)", STRIPE_CHECKOUT_URL)

st.sidebar.write("---")
if st.sidebar.button("Esci (Logout)"):
    st.session_state["autenticato"] = False
    st.rerun()

# --- FUNZIONI CACHE RAPIDE MULTI-TENANT ---
@st.cache_data(ttl=60)
def get_cached_riepilogo(az_id):
    with get_db_connection() as conn:
        with conn.cursor() as c:
            c.execute("""
                SELECT 
                    COALESCE(SUM(CASE WHEN tipo='CARICO' THEN malto_kg ELSE -malto_kg END), 0),
                    COALESCE(SUM(CASE WHEN tipo='CARICO' THEN luppolo_kg ELSE -luppolo_kg END), 0),
                    COALESCE(SUM(CASE WHEN tipo='CARICO' THEN lievito_kg ELSE -lievito_kg END), 0)
                FROM materie_prime WHERE azienda_id=%s;
            """, (az_id,))
            mp = c.fetchone()
            c.execute("""
                SELECT 
                    COALESCE(SUM(CASE WHEN tipo='CARICO' THEN quantita ELSE -quantita END), 0),
                    COALESCE(SUM(CASE WHEN tipo='CARICO' THEN litri_totali ELSE -litri_totali END), 0)
                FROM birra_condizionata WHERE azienda_id=%s;
            """, (az_id,))
            bc = c.fetchone()
    return float(mp[0]), float(mp[1]), float(mp[2]), int(bc[0]), float(bc[1])

@st.cache_data(ttl=60)
def get_cached_ultimi_costi(az_id):
    with get_db_connection() as conn:
        df = pd.read_sql_query("""
            SELECT 
                COALESCE(NULLIF(costo_malto_kg, 0), 1.40) as c_malto,
                COALESCE(NULLIF(costo_luppolo_kg, 0), 28.00) as c_luppolo,
                COALESCE(NULLIF(costo_lievito_kg, 0), 65.00) as c_lievito
            FROM materie_prime 
            WHERE azienda_id=%s AND tipo='CARICO' AND (malto_kg > 0 OR luppolo_kg > 0 OR lievito_kg > 0)
            ORDER BY id DESC LIMIT 1;
        """, conn, params=(az_id,))
    if not df.empty:
        return float(df.iloc[0]["c_malto"]), float(df.iloc[0]["c_luppolo"]), float(df.iloc[0]["c_lievito"])
    return 1.40, 28.00, 65.00

# --- FUNZIONI DI UTILITÀ PARSING XML ---
def trova_testo_nodo(elemento, tags):
    if elemento is None:
        return ""
    for tag in tags:
        for el in elemento.iter():
            tag_pulito = el.tag.split("}")[-1] if "}" in el.tag else el.tag
            if tag_pulito.lower() == tag.lower() and el.text:
                return el.text.strip()
    return ""

def estrai_da_descrizione(desc: str, qta_pz: float, prezzo_un: float = 0.0):
    d = desc.upper()
    kg_tot = qta_pz
    m_kg = re.search(r"(\d+(?:[.,]\d+)?)\s*(?:KG|CHILI)", d)
    m_g = re.search(r"(\d+(?:[.,]\d+)?)\s*(?:G|GR|GRAMMI)\b", d)

    if m_kg:
        kg_tot = float(m_kg.group(1).replace(",", ".")) * qta_pz
    elif m_g:
        kg_tot = (float(m_g.group(1).replace(",", ".")) / 1000.0) * qta_pz

    costo_reale_kg = (prezzo_un * qta_pz) / kg_tot if kg_tot > 0 and prezzo_un > 0 else 0.0

    chiavi_lievito = ["LIEVITO", "YEAST", "FERMENTO", "FERMENTIS", "SAFEBREW", "SAFBREW", "SAFALE", "SAFLAGER", "LALLEMAND", "BE-256", "WB-06", "S-04", "US-05", "T-58"]
    if any(k in d for k in chiavi_lievito):
        return ("LIEVITO", kg_tot, costo_reale_kg)

    chiavi_malto = ["MALTO", "PILSNER", "WEYERMANN", "FRUMENTO", "PALE", "CARA", "CRYSTAL", "MUNICH", "ZUCCHERO CANDITO", "SUGAR CANDY", "CANDI SUGAR", "ZUCCHERO BRUNO", "DESTROSIO"]
    if any(k in d for k in chiavi_malto):
        return ("MALTO", kg_tot, costo_reale_kg)

    chiavi_luppolo = ["LUPPOLO", "HOP", "T90", "T-90", "PELLETS", "MAGNUM", "PERLE", "MOSAIC", "CASCADE", "CITRA", "SAAZ", "STYRIAN", "GOLDING"]
    if any(k in d for k in chiavi_luppolo):
        return ("LUPPOLO", kg_tot, costo_reale_kg)

    return ("ALTRO", 0.0, 0.0)

def estrai_birra_da_vendita(desc: str):
    d = desc.upper()
    if any(k in d for k in ["CAUZIONE", "TRASPORTO", "SPESE", "BICCHIER", "TEKU", "SPEDIZIONE"]):
        return None
    for l, f in [(30, "Fusto 30L"), (25, "Fusto 25L"), (24, "Fusto 24L"), (20, "Fusto 20L")]:
        if str(l) in d and any(k in d for k in ["LT", "LITR", "FUST", "POLYKEG", "DOLIUM"]):
            return (f, float(l))
    if "0.33" in d or "33CL" in d or "33 CL" in d or "0,33" in d or "BOTT" in d:
        return ("Bottiglia 0.33L", 0.33)
    if "0.75" in d or "75CL" in d or "75 CL" in d:
        return ("Bottiglia 0.75L", 0.75)
    return None

def genera_file_ics(titolo, descrizione, data_scadenza):
    dt_str = data_scadenza.strftime("%Y%m%d")
    return f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//BrewDesk//IT
BEGIN:VEVENT
SUMMARY:{titolo}
DESCRIPTION:{descrizione}
DTSTART;VALUE=DATE:{dt_str}
DTEND;VALUE=DATE:{dt_str}
END:VEVENT
END:VCALENDAR""".encode("utf-8")

# --- HEADER APP ---
col_head1, col_head2 = st.columns([1.2, 8])
with col_head1:
    if os.path.exists(LOGO_FILENAME):
        st.image(LOGO_FILENAME, width=80)
with col_head2:
    st.title("BrewDesk — Microbrewery Management")

malto, luppolo, lievito, tot_confezioni, tot_litri_finiti = get_cached_riepilogo(AZIENDA_ID)

c1, c2, c3, c4 = st.columns(4)
c1.metric("Malto & Zuccheri", f"{malto:.1f} kg")
c2.metric("Luppoli", f"{luppolo:.2f} kg")
c3.metric("Lieviti", f"{lievito:.3f} kg")
c4.metric("Birra Finita", f"{tot_litri_finiti:.1f} LT")

st.divider()

tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs([
    "📥 Carico Acquisti XML",
    "🏷️️ Imballaggi",
    "⚗️ Sala Cottura & Allegato I",
    "📦 Confezionamento Misto",
    "🚚 Vendite (XML & Manuale)",
    "🏛️ Giacenze Magazzino",
    "⏰ Scadenze Dogane (2803/2813)"
])

# TAB 1: ACQUISTI XML
with tab1:
    st.subheader("Carico Automatico Materie Prime da Fatture Elettroniche (XML)")
    up_xmls = st.file_uploader("Trascina file XML fatture acquisto", type=["xml"], accept_multiple_files=True, key="xml_acq")
    c_medio = st.number_input("Costo medio indicativo (€/kg)", value=1.40, step=0.1)

    if up_xmls and st.button("Elabora e Carica Fatture"):
        carichi, tm, tl, ty = 0, 0.0, 0.0, 0.0
        with get_db_connection() as conn:
            with conn.cursor() as c:
                for up_xml in up_xmls:
                    try:
                        content = up_xml.read()
                        root = ET.fromstring(content)
                        cedente = root.find(".//DatiAnagraficiCedente")
                        mitt = trova_testo_nodo(cedente, ["Denominazione", "Cognome"]) if cedente is not None else up_xml.name
                        ndoc = trova_testo_nodo(root, ["Numero"]) or "N.D."
                        ddoc = trova_testo_nodo(root, ["Data"]) or datetime.now().strftime("%Y-%m-%d")
                        rif = f"Fatt. {ndoc}"

                        c.execute("SELECT id FROM materie_prime WHERE azienda_id=%s AND riferimento=%s LIMIT 1;", (AZIENDA_ID, rif))
                        if c.fetchone():
                            st.warning(f"⚠️ Documento {ndoc} ({mitt}) già caricato! Saltato.")
                            continue

                        rm, rl, ry = 0.0, 0.0, 0.0
                        cm_kg, cl_kg, cy_kg = 1.40, 28.00, 65.00
                        for el in root.iter():
                            if el.tag.split("}")[-1] == "DettaglioLinee":
                                d = trova_testo_nodo(el, ["Descrizione"])
                                q = float(trova_testo_nodo(el, ["Quantita"]).replace(",", ".") or 0.0)
                                pu = float(trova_testo_nodo(el, ["PrezzoUnitario"]).replace(",", ".") or 0.0)
                                tipo, p, ceff = estrai_da_descrizione(d, q, pu)
                                if tipo == "MALTO":
                                    rm += p
                                    if ceff > 0: cm_kg = ceff
                                elif tipo == "LUPPOLO":
                                    rl += p
                                    if ceff > 0: cl_kg = ceff
                                elif tipo == "LIEVITO":
                                    ry += p
                                    if ceff > 0: cy_kg = ceff

                        c.execute("""
                            INSERT INTO materie_prime (azienda_id, tipo, data, riferimento, azienda, malto_kg, luppolo_kg, lievito_kg, costo_malto_kg, costo_luppolo_kg, costo_lievito_kg, costo_kg_medio)
                            VALUES (%s, 'CARICO', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
                        """, (AZIENDA_ID, ddoc, rif, mitt, rm, rl, ry, cm_kg, cl_kg, cy_kg, c_medio))
                        carichi += 1
                        tm += rm; tl += rl; ty += ry
                    except Exception as e:
                        st.error(f"Errore su {up_xml.name}: {e}")
                conn.commit()
        if carichi > 0:
            st.cache_data.clear()
            st.success(f"Caricate {carichi} fatture: +{tm:.1f} kg Malto/Zuccheri, +{tl:.2f} kg Luppolo, +{ty:.3f} kg Lievito!")
            st.rerun()

# TAB 2: IMBALLAGGI
with tab2:
    st.subheader("Magazzino Imballaggi & Packaging")
    with st.form("imb_f"):
        ci1, ci2, ci3 = st.columns(3)
        with ci1: di = st.date_input("Data").strftime("%Y-%m-%d")
        with ci2: ai = st.selectbox("Articolo", ["Bottiglie 0.33L vuote", "Bottiglie 0.75L vuote", "Tappi a corona", "Etichette", "Scatole / Cartoni", "Fusti vuoti 20L", "Fusti vuoti 24L", "Fusti vuoti 25L", "Fusti vuoti 30L"])
        with ci3: qi = st.number_input("Quantità (pz)", min_value=1, step=100)
        pu_i = st.number_input("Costo Unitario (€/pz)", min_value=0.001, value=0.25, step=0.01)
        if st.form_submit_button("Carica Imballaggi"):
            with get_db_connection() as conn:
                with conn.cursor() as c:
                    c.execute("INSERT INTO imballaggi (azienda_id, tipo_movimento, data, riferimento, articolo, quantita, costo_unitario) VALUES (%s, 'CARICO', %s, 'ACQUISTO', %s, %s, %s);", (AZIENDA_ID, di, ai, qi, pu_i))
                conn.commit()
            st.cache_data.clear()
            st.success("Imballaggi registrati!")
            st.rerun()

    with get_db_connection() as conn:
        df_i = pd.read_sql_query("SELECT articolo, SUM(CASE WHEN tipo_movimento='CARICO' THEN quantita ELSE -quantita END) as giacenza_pz FROM imballaggi WHERE azienda_id=%s GROUP BY articolo;", conn, params=(AZIENDA_ID,))
        st.dataframe(df_i, use_container_width=True)

# TAB 3: SALA COTTURA, ALLEGATO I & CONSUMI ENERGETICI
with tab3:
    st.subheader("⚗️ Sala Cottura: Allegato I, Contalitri & Consumi Energetici")
    c_m_def, c_l_def, c_y_def = get_cached_ultimi_costi(AZIENDA_ID)

    with st.form("form_cotta_allegato1"):
        col_c1, col_c2, col_c3, col_c4 = st.columns(4)
        with col_c1:
            data_prev = st.date_input("Data Preventiva Cotta (Comunicazione Dogane)", value=datetime.now())
        with col_c2:
            data_eff = st.date_input("Data Effettiva Produzione", value=datetime.now())
        with col_c3:
            num_c = st.text_input("N° Cotta", value="C26-01")
        with col_c4:
            lotto_m = st.text_input("Lotto Mosto Sfuso", value=f"LOTTO-{datetime.now().strftime('%y%m%d')}")

        stile_b = st.text_input("Stile Birra (es. Blonde, Dubbel, Golden Ale, APA)", value="Blonde")

        st.markdown("#### 📟 Contalitri Fiscale Dogane & Volumi Mosto")
        cl1, cl2, cl3 = st.columns(3)
        with cl1: cli = st.number_input("Lettura Iniziale Contalitri", min_value=0.0, step=10.0, value=0.0)
        with cl2: clf = st.number_input("Lettura Finale Contalitri", min_value=0.0, step=10.0, value=500.0)
        with cl3:
            diff_cl = max(0.0, clf - cli)
            st.metric("Volume Rilevato da Contalitri", f"{diff_cl:.1f} LT")

        litri_m = st.number_input("Litri Mosto Reali in Fermentatore (LT)", min_value=0.0, step=10.0, value=diff_cl if diff_cl > 0 else 500.0)
        plato_m = st.number_input("Grado Plato (°P)", min_value=0.0, step=0.1, value=12.0)

        # Calcolo Accisa Dogane Dovuta
        ettogradi_cotta = (litri_m * plato_m) / 100.0
        accisa_dovuta_calc = ettogradi_cotta * ALIQUOTA_ACCISA_PLATO

        st.markdown("#### ⚡ Consumi Energetici Obbligatori (Allegato I Dogane)")
        ce1, ce2, ce3 = st.columns(3)
        with ce1:
            gas_mc = st.number_input("Consumo Gas GPL / Metano (Standard mc)", min_value=0.0, step=0.5, value=14.5, help="Metri cubi consumati per riscaldamento sala cottura")
        with ce2:
            kwh_consumati = st.number_input("Consumo Energia Elettrica (kWh)", min_value=0.0, step=1.0, value=45.0, help="Consumi elettrici mulino, pompe e gruppi frigo")
        with ce3:
            st.metric("Accisa Dogane Dovuta Cotta", f"€ {accisa_dovuta_calc:.2f}", help=f"Ettogradi: {ettogradi_cotta:.2f} °E")

        st.markdown("#### 🌾 Materie Prime Impiegate")
        cm1, cm2 = st.columns(2)
        with cm1:
            malto_k = st.number_input("Kg Malto & Fermentabili Macinati (kg)", min_value=0.0, step=5.0, value=100.0)
            lup_g = st.number_input("Grammi Luppolo Impiegato (g)", min_value=0.0, step=50.0, value=1000.0)
        with cm2:
            liev_g = st.number_input("Grammi Lievito Nuovo Impiegato (g) [0 se ripitching]", min_value=0.0, step=1.0, value=11.5)

        tot_spesa_mp = (malto_k * c_m_def) + ((lup_g / 1000.0) * c_l_def) + ((liev_g / 1000.0) * c_y_def)
        costo_lt_mosto = (tot_spesa_mp / litri_m) if litri_m > 0 else 0.0
        st.info(f"💵 **Costo Materie Prime:** € {tot_spesa_mp:.2f} | **Costo al Litro Mosto:** € {costo_lt_mosto:.3f} / LT")

        if st.form_submit_button("Salva Cotta in Allegato I & Scarica Materie Prime", type="primary"):
            with get_db_connection() as conn:
                with conn.cursor() as c:
                    c.execute("""
                        INSERT INTO registro_mosto (
                            azienda_id, data, data_preventiva, cotta_num, tipo_birra, litri_mosto, grado_plato, lotto_sfuso,
                            contalitri_inizio, contalitri_fine, malto_usato_kg, luppolo_usato_kg, lievito_usato_kg,
                            consumo_gas_mc, consumo_elettrico_kwh, accisa_dovuta_euro, costo_totale_cotta, costo_litro_mosto
                        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
                    """, (
                        AZIENDA_ID, data_eff.strftime("%Y-%m-%d"), data_prev.strftime("%Y-%m-%d"), num_c, stile_b, litri_m, plato_m, lotto_m,
                        cli, clf, malto_k, lup_g / 1000.0, liev_g / 1000.0, gas_mc, kwh_consumati, accisa_dovuta_calc, tot_spesa_mp, costo_lt_mosto
                    ))
                    c.execute("""
                        INSERT INTO materie_prime (azienda_id, tipo, data, riferimento, azienda, malto_kg, luppolo_kg, lievito_kg)
                        VALUES (%s, 'SCARICO', %s, %s, 'COTTA PRODUZIONE', %s, %s, %s);
                    """, (AZIENDA_ID, data_eff.strftime("%Y-%m-%d"), f"Cotta {num_c} - {lotto_m}", malto_k, lup_g / 1000.0, liev_g / 1000.0))
                conn.commit()
            st.cache_data.clear()
            st.success(f"Cotta {num_c} salvata! Accisa generata: € {accisa_dovuta_calc:.2f} - Consumi energetici registrati.")
            st.rerun()

    st.write("---")
    st.markdown("#### Registro Cotte & Consumi Energetici Ufficiale (Allegato I)")
    with get_db_connection() as conn:
        df_allegato1 = pd.read_sql_query("""
            SELECT 
                id, data_preventiva as "Data Preventiva", data as "Data Cotta", cotta_num as "N° Cotta", tipo_birra as "Stile",
                litri_mosto as "Litri Mosto", grado_plato as "°Plato", accisa_dovuta_euro as "Accisa Dovuta (€)",
                consumo_gas_mc as "Gas (mc)", consumo_elettrico_kwh as "Energia (kWh)", lotto_sfuso as "Lotto"
            FROM registro_mosto WHERE azienda_id=%s ORDER BY id DESC;
        """, conn, params=(AZIENDA_ID,))
        st.dataframe(df_allegato1, use_container_width=True)

# TAB 4: CONFEZIONAMENTO MISTO
with tab4:
    st.subheader("📦 Confezionamento Misto Cotta (Fusti e Bottiglie Simultanei)")
    with get_db_connection() as conn:
        df_cotte_disp = pd.read_sql_query("SELECT id, cotta_num, lotto_sfuso, tipo_birra, litri_mosto, grado_plato, costo_litro_mosto FROM registro_mosto WHERE azienda_id=%s ORDER BY id DESC LIMIT 20;", conn, params=(AZIENDA_ID,))

    if not df_cotte_disp.empty:
        opts = [f"ID {r['id']} | Cotta {r['cotta_num']} ({r['tipo_birra']}) - {r['litri_mosto']} LT - °P {r['grado_plato']}" for _, r in df_cotte_disp.iterrows()]
        sel_c = st.selectbox("Seleziona Cotta:", opts)
        id_c = int(sel_c.split("|")[0].replace("ID", "").strip())
        r_sel = df_cotte_disp[df_cotte_disp["id"] == id_c].iloc[0]
        litri_iniziali = float(r_sel["litri_mosto"])
        plato_rif = float(r_sel["grado_plato"])
        lotto_def = str(r_sel["lotto_sfuso"])
        costo_lt_def = float(r_sel.get("costo_litro_mosto", 1.10) or 1.10)
    else:
        litri_iniziali, plato_rif, lotto_def, costo_lt_def = 500.0, 12.0, "LOTTO-2601", 1.10

    with st.form("conf_misto_f"):
        cc1, cc2, cc3 = st.columns(3)
        with cc1: d_conf = st.date_input("Data Confezionamento", value=datetime.now())
        with cc2: l_conf = st.text_input("Lotto Confezionato", value=lotto_def)
        with cc3: c_lt = st.number_input("Costo Produzione (€/LT)", min_value=0.01, value=costo_lt_def, step=0.05)

        st.markdown("##### 🛢️ Fusti")
        f1, f2, f3, f4 = st.columns(4)
        with f1: q20 = st.number_input("Fusti 20L", min_value=0, value=0)
        with f2: q24 = st.number_input("Fusti 24L", min_value=0, value=0)
        with f3: q25 = st.number_input("Fusti 25L", min_value=0, value=0)
        with f4: q30 = st.number_input("Fusti 30L", min_value=0, value=0)

        st.markdown("##### 🍾 Bottiglie")
        b1, b2 = st.columns(2)
        with b1: q33 = st.number_input("Bottiglie 0.33L (singoli pz)", min_value=0, step=12, value=0)
        with b2: q75 = st.number_input("Bottiglie 0.75L (singoli pz)", min_value=0, step=6, value=0)

        lt_teorici = (q20 * 20.0) + (q24 * 24.0) + (q25 * 25.0) + (q30 * 30.0) + (q33 * 0.33) + (q75 * 0.75)
        scarto_teorico = max(0.0, litri_iniziali - lt_teorici)

        st.write("---")
        v1, v2, v3 = st.columns(3)
        with v1: lt_eff = st.number_input("Litri Effettivi Confezionati (LT)", min_value=0.0, value=float(lt_teorici))
        with v2:
            etto_tot = (lt_eff * plato_rif) / 100.0
            st.metric("Ettogradi Fiscali (°E)", f"{etto_tot:.2f} °E")
        with v3: scarto_reale = st.number_input("Scarto Reale (LT)", min_value=0.0, value=float(scarto_teorico))

        if st.form_submit_button("Carica Formati a Magazzino", type="primary"):
            if lt_eff <= 0:
                st.error("Inserisci almeno un formato confezionato.")
            else:
                d_str = d_conf.strftime("%Y-%m-%d")
                fattore = (lt_eff / lt_teorici) if lt_teorici > 0 else 1.0
                movs = []
                if q20 > 0: movs.append(("Fusto 20L", q20, (q20 * 20.0) * fattore, "Fusti vuoti 20L"))
                if q24 > 0: movs.append(("Fusto 24L", q24, (q24 * 24.0) * fattore, "Fusti vuoti 24L"))
                if q25 > 0: movs.append(("Fusto 25L", q25, (q25 * 25.0) * fattore, "Fusti vuoti 25L"))
                if q30 > 0: movs.append(("Fusto 30L", q30, (q30 * 30.0) * fattore, "Fusti vuoti 30L"))
                if q33 > 0: movs.append(("Bottiglia 0.33L", q33, (q33 * 0.33) * fattore, "Bottiglie 0.33L vuote"))
                if q75 > 0: movs.append(("Bottiglia 0.75L", q75, (q75 * 0.75) * fattore, "Bottiglie 0.75L vuote"))

                with get_db_connection() as conn:
                    with conn.cursor() as c:
                        for idx, (fmt, qta, l_riga, art_imb) in enumerate(movs):
                            sc = scarto_reale if idx == 0 else 0.0
                            c.execute("""
                                INSERT INTO birra_condizionata (azienda_id, tipo, data, lotto, formato, quantita, litri_totali, grado_plato, ettogradi, scarto_litri, costo_produzione_litro, documento_rif)
                                VALUES (%s, 'CARICO', %s, %s, %s, %s, %s, %s, %s, %s, %s, 'CONFEZIONAMENTO');
                            """, (AZIENDA_ID, d_str, l_conf, fmt, qta, l_riga, plato_rif, (l_riga * plato_rif) / 100.0, sc, c_lt))
                            c.execute("INSERT INTO imballaggi (azienda_id, tipo_movimento, data, riferimento, articolo, quantita) VALUES (%s, 'SCARICO', %s, %s, %s, %s);", (AZIENDA_ID, d_str, f"Lotto {l_conf}", art_imb, qta))
                            if "Bottiglia" in fmt:
                                c.execute("INSERT INTO imballaggi (azienda_id, tipo_movimento, data, riferimento, articolo, quantita) VALUES (%s, 'SCARICO', %s, %s, 'Tappi a corona', %s);", (AZIENDA_ID, d_str, f"Lotto {l_conf}", qta))
                                c.execute("INSERT INTO imballaggi (azienda_id, tipo_movimento, data, riferimento, articolo, quantita) VALUES (%s, 'SCARICO', %s, %s, 'Etichette', %s);", (AZIENDA_ID, d_str, f"Lotto {l_conf}", qta))
                    conn.commit()
                st.cache_data.clear()
                st.success(f"Caricati {lt_eff:.1f} LT a magazzino! Scarto registrato: {scarto_reale:.1f} LT.")
                st.rerun()

# TAB 5: VENDITE
with tab5:
    st.subheader("🚚 Scarico Vendite Birra (Fatture Elettroniche XML)")
    up_v_xml = st.file_uploader("Trascina qui le fatture XML emesse", type=["xml"], accept_multiple_files=True, key="xml_vend")

    if up_v_xml and st.button("Elabora e Scarica Fatture Emesse"):
        tot_sc, tot_l = 0, 0.0
        with get_db_connection() as conn:
            with conn.cursor() as c:
                for up_xml in up_v_xml:
                    try:
                        content = up_xml.read()
                        root = ET.fromstring(content)
                        cess = root.find(".//DatiAnagraficiCessionario")
                        clie = trova_testo_nodo(cess, ["Denominazione", "Cognome"]) if cess is not None else "Cliente"
                        ndoc = trova_testo_nodo(root, ["Numero"]) or "N.D."
                        ddoc = trova_testo_nodo(root, ["Data"]) or datetime.now().strftime("%Y-%m-%d")
                        rif_v = f"Fatt. {ndoc} - {clie}"

                        c.execute("SELECT id FROM birra_condizionata WHERE azienda_id=%s AND documento_rif=%s LIMIT 1;", (AZIENDA_ID, rif_v))
                        if c.fetchone():
                            st.warning(f"⚠️ Fattura {ndoc} già elaborata! Saltata.")
                            continue

                        for el in root.iter():
                            if el.tag.split("}")[-1] == "DettaglioLinee":
                                d = trova_testo_nodo(el, ["Descrizione"])
                                q = int(float(trova_testo_nodo(el, ["Quantita"]).replace(",", ".") or 1))
                                pu = float(trova_testo_nodo(el, ["PrezzoUnitario"]).replace(",", ".") or 0.0)
                                b_info = estrai_birra_da_vendita(d)
                                if b_info:
                                    fmt_v, lt_u = b_info
                                    lt_r = q * lt_u
                                    c.execute("""
                                        INSERT INTO birra_condizionata (azienda_id, tipo, data, lotto, formato, quantita, litri_totali, costo_produzione_litro, documento_rif)
                                        VALUES (%s, 'SCARICO', %s, '-', %s, %s, %s, %s, %s);
                                    """, (AZIENDA_ID, ddoc, fmt_v, q, lt_r, pu, rif_v))
                                    tot_sc += 1
                                    tot_l += lt_r
                    except Exception as e:
                        st.error(f"Errore su {up_xml.name}: {e}")
                conn.commit()
        if tot_sc > 0:
            st.cache_data.clear()
            st.success(f"Registrati {tot_sc} scarichi vendita per {tot_l:.1f} Litri!")
            st.rerun()

# TAB 6: GIACENZE MAGAZZINO
with tab6:
    st.subheader("🏛️ Giacenze Magazzino Prodotti Finiti")
    with get_db_connection() as conn:
        df_pf = pd.read_sql_query("""
            SELECT 
                formato as "Formato", 
                COALESCE(SUM(CASE WHEN tipo='CARICO' THEN quantita ELSE -quantita END), 0) as "Pezzi",
                ROUND(COALESCE(SUM(CASE WHEN tipo='CARICO' THEN litri_totali ELSE -litri_totali END), 0)::numeric, 1) as "Litri"
            FROM birra_condizionata WHERE azienda_id=%s GROUP BY formato ORDER BY formato;
        """, conn, params=(AZIENDA_ID,))
        st.dataframe(df_pf, use_container_width=True)

        st.markdown("#### 🔍 Dettaglio Movimentazioni Magazzino")
        df_det = pd.read_sql_query("""
            SELECT id, data as "Data", tipo as "Tipo", lotto as "Lotto", formato as "Formato", quantita as "Pz", litri_totali as "Litri", documento_rif as "Rif"
            FROM birra_condizionata WHERE azienda_id=%s ORDER BY id DESC;
        """, conn, params=(AZIENDA_ID,))
        st.dataframe(df_det, use_container_width=True)

        if not df_det.empty:
            col_d1, col_d2 = st.columns([3, 1])
            with col_d1:
                opts_del = [f"ID {r['id']} | {r['Data']} - {r['Tipo']} {r['Pz']} pz ({r['Formato']} - {r['Litri']} LT) - {r['Rif']}" for _, r in df_det.iterrows()]
                sel_m_del = st.selectbox("Seleziona movimento errato da eliminare:", opts_del)
                id_m_del = int(sel_m_del.split("|")[0].replace("ID", "").strip())
            with col_d2:
                st.write("")
                st.write("")
                if st.button("🗑️ Elimina Movimento", type="primary"):
                    with conn.cursor() as c:
                        c.execute("DELETE FROM birra_condizionata WHERE azienda_id=%s AND id=%s;", (AZIENDA_ID, id_m_del))
                    conn.commit()
                    st.cache_data.clear()
                    st.success("Movimento eliminato!")
                    st.rerun()

# TAB 7: SCADENZE DOGANE (2803/2813)
with tab7:
    st.subheader("⏰ Scadenze Dogane: Tributo 2803 (Accisa) e 2813 (Diritto Licenza)")
    col_s1, col_s2 = st.columns(2)
    with col_s1:
        with st.form("form_scad"):
            trib = st.selectbox("Tributo Doganale F24", ["2803 - Accisa Birra (Mensile entro il 16)", "2813 - Diritto Licenza Annuale (Fabbricazione/Deposito)"])
            m_scad = st.selectbox("Periodo di Riferimento", ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"])
            anno_s = st.number_input("Anno", min_value=2024, max_value=2030, value=datetime.now().year)
            d_scad = st.date_input("Data Scadenza F24", value=datetime(anno_s, 12, 16) if "2813" in trib else datetime(anno_s, datetime.now().month, 16))
            imp_scad = st.number_input("Importo Dovuto (€)", min_value=0.0, step=25.0, value=250.0 if "2803" in trib else 68.0)
            note_s = st.text_input("Note", value="Versamento F24 Dogane")

            if st.form_submit_button("Salva Scadenza"):
                cod_trib = "2803" if "2803" in trib else "2813"
                with get_db_connection() as conn:
                    with conn.cursor() as c:
                        c.execute("""
                            INSERT INTO scadenze_accise (azienda_id, periodo_riferimento, data_scadenza, codice_tributo, importo_dovuto, note)
                            VALUES (%s, %s, %s, %s, %s, %s);
                        """, (AZIENDA_ID, f"{m_scad} {anno_s}", d_scad.strftime("%Y-%m-%d"), cod_trib, imp_scad, note_s))
                    conn.commit()
                st.cache_data.clear()
                st.success("Scadenza salvata!")
                st.rerun()

    with col_s2:
        with get_db_connection() as conn:
            df_sc = pd.read_sql_query("SELECT id, periodo_riferimento, data_scadenza, codice_tributo, importo_dovuto FROM scadenze_accise WHERE azienda_id=%s ORDER BY data_scadenza ASC;", conn, params=(AZIENDA_ID,))
        if not df_sc.empty:
            for _, r in df_sc.iterrows():
                dt_sc = pd.to_datetime(r["data_scadenza"]).date()
                diff_gg = (dt_sc - datetime.now().date()).days
                with st.expander(f"📌 Tributo {r['codice_tributo']} - {dt_sc.strftime('%d/%m/%Y')} (€ {r['importo_dovuto']:.2f})"):
                    st.write(f"Mancano {diff_gg} giorni alla scadenza.")
                    titolo_g = urllib.parse.quote(f"F24 Trib. {r['codice_tributo']} BrewDesk - € {r['importo_dovuto']:.2f}")
                    gcal_url = f"https://calendar.google.com/calendar/render?action=TEMPLATE&text={titolo_g}&dates={dt_sc.strftime('%Y%m%d')}/{dt_sc.strftime('%Y%m%d')}"
                    st.link_button("🌐 Sincronizza su Google Calendar", gcal_url)

            st.write("---")
            opts_sc_del = [f"ID {r['id']} | Trib. {r['codice_tributo']} ({r['data_scadenza']}) - € {r['importo_dovuto']:.2f}" for _, r in df_sc.iterrows()]
            sel_s_del = st.selectbox("Cancella scadenza errata:", opts_sc_del)
            id_s_del = int(sel_s_del.split("|")[0].replace("ID", "").strip())
            if st.button("🗑️ Elimina Scadenza Selezionata", type="primary"):
                with get_db_connection() as conn:
                    with conn.cursor() as c:
                        c.execute("DELETE FROM scadenze_accise WHERE azienda_id=%s AND id=%s;", (AZIENDA_ID, id_s_del))
                    conn.commit()
                st.cache_data.clear()
                st.success("Scadenza rimossa!")
                st.rerun()
